services:
  - docker

dist: trusty
sudo: false
cache: bundler

git:
  depth: false

test: &test
  stage: Test
  language: ruby
  before_install:
    - gem install bundler
    - gem update --system
  script: bundle exec rake test

jobs:
  include:
    - <<: *test
      rvm: 2.6.5
    - <<: *test
      rvm: 2.5.7
    - <<: *test
      rvm: 2.4.8
    - <<: *test
      rvm: jruby-9.2.8.0
    - <<: *test
      rvm: ruby-head

    - stage: coditsu
      language: ruby
      rvm: 2.6.5
      before_install:
        - gem update --system
        - gem install bundler
      script: \curl -sSL https://api.coditsu.io/run/ci | bash

stages:
  - test
  - coditsu
